### PR TITLE
Fix transmitting of LDAP attributes

### PR DESCRIPTION
**Pull request by spaceone**

### CODE REVIEW

**Comment by spaceone** [comment]
I am really sorry for this! It seems to be a bug in UCS that 'true' is not accepted but only 'TRUE'. At least this is a workaround.

**Comment by crohr** [comment]
Sorry I didn't see your PR before, I've already fixed the script to use `--set simplesamlAttributes=TRUE` (without quotes). I suppose this is ok.

**Comment by spaceone** [comment]
Yes.

**Comment by crohr** [comment]
OK, thanks again!

**Pull request closed without merging**
