### PR TITLE
Some improovements

### PR DESCRIPTION
**Pull request by spaceone**

### CODE REVIEW

**Comment by crohr** [comment]
@spaceone thanks for the fixes. Do you think `ucr set saml/idp/ldap/get_attributes="${saml_idp_ldap_get_attributes}, 'sn', 'givenName'"` should work?

**Comment by spaceone** [comment]
Yes, here is the proove:
```
root@xen3:~# eval "$(ucr shell)"
root@xen3:~# echo "${saml_idp_ldap_get_attributes}"
'uid', 'mailPrimaryAddress', 'enabledServiceProviderIdentifier'
root@xen3:~# ucr set saml/idp/ldap/get_attributes="${saml_idp_ldap_get_attributes}, 'sn', 'givenName'"
Setting saml/idp/ldap/get_attributes
Multifile: /etc/simplesamlphp/authsources.php
root@xen3:~# eval "$(ucr shell)"
root@xen3:~# echo "${saml_idp_ldap_get_attributes}"
'uid', 'mailPrimaryAddress', 'enabledServiceProviderIdentifier', 'sn', 'givenName'
```

I think this is better because you don't remove user-modified changes then.

**Comment by crohr** [comment]
Well, I've noticed that the change takes effect (`/etc/simplesamlphp/authsources.php` is correctly updated), but then when I do the request the SAML response does not contain the requested attributes (only `uid` and `mailPrimaryAddress` are returned -- http://chunk.io/f/5fc29a183fb541fd985bc0effb15321a)

**Comment by crohr** [comment]
And here are the settings when I look in the management UI:
saml-provider-settings

**Comment by spaceone** [comment]
Why doesn't the list contain uid and univentionServiceProviderEnabled.
What is the output of `univention-ldapsearch univentionObjectType=saml/serviceprovider -LLL | ldapsearch-wrapper`?

**Comment by crohr** [comment]
http://chunk.io/f/f8b43d2eaff14c81a4421086adb26546 (I removed `givenName` since then)

**Comment by spaceone** [comment]
Please execute:
`udm saml/serviceprovider modify --dn 'SAMLServiceProviderIdentifier=openproject,cn=saml-serviceprovider,cn=univention,dc=openproject,dc=intranet' --set simplesamlAttributes=TRUE`

**Comment by crohr** [comment]
Looks like that did the trick, I now get the proper attributes in the response. Is that simply because of the `true/TRUE` difference? Weird that the management UI and LDAP showed it correctly set.

**Comment by spaceone** [comment]
Yes, the reason is that we have some 'syntax classes' which basically do a mapping of user-input strings to what is actually written into LDAP. The syntax class for this property is broken so the value 'true' was written to LDAP. And the handler/listener module which evaluated the flag only checks for 'TRUE' (which should have been adjusted by the syntax class). Using UMC this works by the way. You could have toggled it twice and it would have worked :)

**Comment by crohr** [comment]
ok ;) I think I tried it, but maybe not. Thanks a lot for your help, it's working now, just need to iron out a few quirks from our side.

**Pull request merged**
